### ISSUE TITLE
0.4.0.1 fails to find architecture independent shared data

### ISSUE THREAD

**Issue by tgurr** [kozec/sc-controller#314]
0.4.0.1 fails to find the architecture independent data in /usr/share.

We support proper cross compilation/environments in our distribution, the architecture dependent data gets installed to /usr/${CHOST}/{bin,include,lib} while the architecture independent data which is shared among the architectures gets installed to /usr/share like usual.

sc-controller 0.3.15 works without any problem but something (regarding the search paths?) seems to have changed in 0.4.0.1 since it now looks for the shared data in /usr/${CHOST}/share instead of /usr/share which would be correct:
```
$ sc-controller 
Traceback (most recent call last):
  File "/usr/x86_64-pc-linux-gnu/lib/python2.7/site-packages/scc/gui/app.py", line 1268, in do_startup
    self.setup_widgets()
  File "/usr/x86_64-pc-linux-gnu/lib/python2.7/site-packages/scc/gui/app.py", line 93, in setup_widgets
    self.builder.add_from_file(os.path.join(self.gladepath, "app.glade"))
GLib.Error: g-file-error-quark: Failed to open file “/usr/x86_64-pc-linux-gnu/share/scc/glade/app.glade”: No such file or directory (4)
Traceback (most recent call last):
  File "/usr/x86_64-pc-linux-gnu/lib/python2.7/site-packages/scc/gui/app.py", line 1301, in do_activate
    self.builder.get_object("window").show()
AttributeError: 'NoneType' object has no attribute 'show'
Traceback (most recent call last):
  File "/usr/x86_64-pc-linux-gnu/lib/python2.7/site-packages/scc/gui/app.py", line 1238, in on_daemon_dead
    self.set_daemon_status("unknown", True)
  File "/usr/x86_64-pc-linux-gnu/lib/python2.7/site-packages/scc/gui/app.py", line 1338, in set_daemon_status
    imgDaemonStatus.set_from_file(icon)
AttributeError: 'NoneType' object has no attribute 'set_from_file'
W UDataManager  enumerate_children_finish for /usr/x86_64-pc-linux-gnu/share/scc/default_profiles failed: g-io-error-quark: Error opening directory '/usr/x86_64-pc-linux-gnu/share/scc/default_profiles': No such file or directory (1)
```

I couldn't find anything obvious in the code but it must be a change between 0.3.15 and 0.4.0.1 that's causing the issue.

**Comment by kozec** [comment]
That's probably caused by #285. What does `python -c 'import sys; print sys.prefix'` says on that very mysteriously unspecified distro?

**Comment by tgurr** [comment]
```
$ python -c 'import sys; print sys.prefix'
/usr/host/bin/../../../etc/env.d/alternatives/python/_current/usr/x86_64-pc-linux-gnu/bin/../../../../../../../../usr/x86_64-pc-linux-gnu/bin/../../../etc/env.d/alternatives/python2/_current/usr/x86_64-pc-linux-gnu/bin/../../../../../../../../usr/x86_64-pc-linux-gnu
```
or in short
```
/usr/x86_64-pc-linux-gnu
```

The distribution in question is Exherbo, you can find more details and rationale about the layout here:

https://exherbo.org/docs/multiarch.txt

Pretty sure it's caused by https://github.com/kozec/sc-controller/pull/285 having had a look at it now. However we'd like to avoid downstream patching as much as possible so it would be nice to get this properly fixed. I'm no Python expert, autotools e.g. has the --datadir which can be different from --prefix, cmake as well. I'm trying to think of any other Python based software installing stuff to /usr/share, https://displaycal.net/ comes to my mind, which seems to work fine across platforms/distributions (Exherbo included). Maybe it's useful to get an idea there. I'm afraid when it comes to providing a solution I can't be of much use, but if there's any fix to test I'm more than willing to do so and provide feedback.

**Comment by kozec** [comment]
I'm not 100% sure, but there is good chance this is missconfiguration of python package. [sys.prefix](https://docs.python.org/2/library/sys.html#sys.prefix) should return _platform independent_ /usr/, not /usr/x86_64-pc-linux-gnu.

I can re-add check and retry with hard-codded path, but you'll probably get same problem with next python-based thing you'll try to install :)

**Comment by kozec** [comment]
Were you able to do anything?

**Comment by tgurr** [comment]
Sorry for the lack of response, I've tried to get an overview how other Python packages do this but I as I'm not a Python programmer I wasn't able to come to a conclusion.
All I can say is that it worked fine with previous versions of sc-controller and there are other packages which we package/install exaclty in the same way and there hasn't been any problem with them being able to find shared data and/or stuff installed outside of sys.prefix.

I also don't think our sys.prefix is wrong because the link you posted mentions include and lib residing under sys.prefix which is the case for our /usr/x86_64-pc-linux-gnu and plain /usr would be wrong in our setup.

**Comment by kozec** [comment]
Ok, so let's keep ti simple and just put /usr/share as worst-case fallback.
